#!/bin/bash

# Script to install local JARs from lib/ directory to local Maven repository
# This allows Maven to compile the project without accessing the private Nexus repository

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB_DIR="$SCRIPT_DIR/lib"

echo "=========================================="
echo "Installing local dependencies to Maven"
echo "=========================================="

# Function to install a JAR to local Maven repository
install_jar() {
    local jar_file="$1"
    local group_id="$2"
    local artifact_id="$3"
    local version="$4"
    
    if [ -f "$jar_file" ]; then
        echo "Installing: $artifact_id"
        mvn install:install-file \
            -Dfile="$jar_file" \
            -DgroupId="$group_id" \
            -DartifactId="$artifact_id" \
            -Dversion="$version" \
            -Dpackaging=jar \
            -DgeneratePom=true \
            -q
    else
        echo "WARNING: File not found: $jar_file"
    fi
}

# Install dependencies from es.altia.regexlan.externo group
echo ""
echo "Installing es.altia.regexlan.externo dependencies..."
install_jar "$LIB_DIR/aopalliance-1.0.jar" "es.altia.regexlan.externo" "aopalliance" "1.0"
install_jar "$LIB_DIR/axis-jaxrpc-1.4.jar" "es.altia.regexlan.externo" "axis-jaxrpc" "1.4"
install_jar "$LIB_DIR/axis-saaj-1.4.jar" "es.altia.regexlan.externo" "axis-saaj" "1.4"
install_jar "$LIB_DIR/batik-all-1.7.jar" "es.altia.regexlan.externo" "batik-all" "1.7"
install_jar "$LIB_DIR/castor-1.3.1.jar" "es.altia.regexlan.externo" "castor" "1.3.1"
install_jar "$LIB_DIR/castor-core-1.3.1.jar" "es.altia.regexlan.externo" "castor-core" "1.3.1"
install_jar "$LIB_DIR/client_afirma-1.0.jar" "es.altia.regexlan.externo" "client_afirma" "1.0"
install_jar "$LIB_DIR/dss-common-2.0.2.jar" "es.altia.regexlan.externo" "dss-common" "2.0.2"
install_jar "$LIB_DIR/dss-document-2.0.2.jar" "es.altia.regexlan.externo" "dss-document" "2.0.2"
install_jar "$LIB_DIR/dss-itext-2.0.2.jar" "es.altia.regexlan.externo" "dss-itext" "2.0.2"
install_jar "$LIB_DIR/dss-service-2.0.2.jar" "es.altia.regexlan.externo" "dss-service" "2.0.2"
install_jar "$LIB_DIR/dss-spi-2.0.2.jar" "es.altia.regexlan.externo" "dss-spi" "2.0.2"
install_jar "$LIB_DIR/DynamicJasper-4.0.3.jar" "es.altia.regexlan.externo" "dynamicJasper" "4.0.3"
install_jar "$LIB_DIR/integra-1.2.2.jar" "es.altia.regexlan.externo" "integra" "1.2.2"
install_jar "$LIB_DIR/jcommon-1.0.8.jar" "es.altia.regexlan.externo" "jcommon" "1.0.8"
install_jar "$LIB_DIR/jcommon-xml-1.0.8.jar" "es.altia.regexlan.externo" "jcommon-xml" "1.0.8"
install_jar "$LIB_DIR/jdbc-stdext-2.0.jar" "es.altia.regexlan.externo" "jdbc-stdext" "2.0"
install_jar "$LIB_DIR/jfreereport-0.8.8.jar" "es.altia.regexlan.externo" "jfreereport" "0.8.8"
install_jar "$LIB_DIR/jodconverter-core-3.0-beta-4.jar" "es.altia.regexlan.externo" "jodconverter-core" "3.0-beta-4"
install_jar "$LIB_DIR/jss-4.2.5.jar" "es.altia.regexlan.externo" "jss" "4.2.5"
install_jar "$LIB_DIR/juh-3.2.1.jar" "es.altia.regexlan.externo" "juh" "3.2.1"
install_jar "$LIB_DIR/libbase-1.2.2.jar" "es.altia.regexlan.externo" "libbase" "1.2.2"
install_jar "$LIB_DIR/libdocbundle-1.2.3.jar" "es.altia.regexlan.externo" "libdocbundle" "1.2.3"
install_jar "$LIB_DIR/libfonts-1.2.3.jar" "es.altia.regexlan.externo" "libfonts" "1.2.3"
install_jar "$LIB_DIR/libformat-1.2.4.jar" "es.altia.regexlan.externo" "libformat" "1.2.4"
install_jar "$LIB_DIR/libformula-1.2.3.jar" "es.altia.regexlan.externo" "libformula" "1.2.3"
install_jar "$LIB_DIR/libloader-1.2.3.jar" "es.altia.regexlan.externo" "libloader" "1.2.3"
install_jar "$LIB_DIR/libserializer-1.2.2.jar" "es.altia.regexlan.externo" "libserializer" "1.2.2"
install_jar "$LIB_DIR/librepository-1.2.3.jar" "es.altia.regexlan.externo" "librepository" "1.2.3"
install_jar "$LIB_DIR/libxml-1.2.2.jar" "es.altia.regexlan.externo" "libxml" "1.2.2"
install_jar "$LIB_DIR/mITyCLibAPI-1.0.4.jar" "es.altia.regexlan.externo" "mITyCLibAPI" "1.0.4"
install_jar "$LIB_DIR/mITyCLibCert-1.0.4.jar" "es.altia.regexlan.externo" "mITyCLibCert" "1.0.4"
install_jar "$LIB_DIR/mITyCLibOCSP-1.0.4.jar" "es.altia.regexlan.externo" "mITyCLibOCSP" "1.0.4"
install_jar "$LIB_DIR/mITyCLibPolicy-1.0.4.jar" "es.altia.regexlan.externo" "mITyCLibPolicy" "1.0.4"
install_jar "$LIB_DIR/mITyCLibTrust-1.0.4.jar" "es.altia.regexlan.externo" "mITyCLibTrust" "1.0.4"
install_jar "$LIB_DIR/pentaho-reporting-3.8.3-GA.jar" "es.altia.regexlan.externo" "pentaho-reporting" "3.8.3-GA"
install_jar "$LIB_DIR/stax-ex-2.1.1.jar" "es.altia.regexlan.externo" "stax-ex" "2.1.1"
install_jar "$LIB_DIR/strutsel-1.0.jar" "es.altia.regexlan.externo" "strutsel" "1.0"
install_jar "$LIB_DIR/strutLocal-1.0.jar" "es.altia.regexlan.externo" "strutLocal" "1.0"
install_jar "$LIB_DIR/taglibs_string-1.0.jar" "es.altia.regexlan.externo" "taglibs_string" "1.0"
install_jar "$LIB_DIR/viafirma-client-2.9.62.jar" "es.altia.regexlan.externo" "viafirma-client" "2.9.62"
install_jar "$LIB_DIR/xml-apis-2.9.1.jar" "es.altia.regexlan.externo" "xml-apis" "2.9.1"
install_jar "$LIB_DIR/annotations-api-1.0.jar" "es.altia.regexlan.externo" "annotations-api" "1.0"
install_jar "$LIB_DIR/avalon-framework-cvs-1.0.jar" "es.altia.regexlan.externo" "avalon-framework-cvs" "1.0"
install_jar "$LIB_DIR/axis-ant-1.0.jar" "es.altia.regexlan.externo" "axis-ant" "1.0"
install_jar "$LIB_DIR/bcmail-jdk16-146-1.0.jar" "es.altia.regexlan.externo" "bcmail-jdk16-146" "1.0"
install_jar "$LIB_DIR/bcprov-jdk16-146-1.0.jar" "es.altia.regexlan.externo" "bcprov-jdk16-146" "1.0"
install_jar "$LIB_DIR/bctsp-jdk16-146-1.0.jar" "es.altia.regexlan.externo" "bctsp-jdk16-146" "1.0"
install_jar "$LIB_DIR/bforeport-1.0.jar" "es.altia.regexlan.externo" "bforeport" "1.0"
install_jar "$LIB_DIR/clienteViaFirmaInbox-1.0.jar" "es.altia.regexlan.externo" "clienteViaFirmaInbox" "1.0"
install_jar "$LIB_DIR/dom-1.0.jar" "es.altia.regexlan.externo" "dom" "1.0"
install_jar "$LIB_DIR/dtdparser-1.0.jar" "es.altia.regexlan.externo" "dtdparser" "1.0"
install_jar "$LIB_DIR/fop-1.0.jar" "es.altia.regexlan.externo" "fop" "1.0"
install_jar "$LIB_DIR/jakarta-oro-1.0.jar" "es.altia.regexlan.externo" "jakarta-oro" "1.0"
install_jar "$LIB_DIR/javamail-crypto-1.0.jar" "es.altia.regexlan.externo" "javamail-crypto" "1.0"
install_jar "$LIB_DIR/javamail-crypto-bouncycastle-smime-1.0.jar" "es.altia.regexlan.externo" "javamail-crypto-bouncycastle-smime" "1.0"
install_jar "$LIB_DIR/jaxrpc-1.0.jar" "es.altia.regexlan.externo" "jaxrpc" "1.0"
install_jar "$LIB_DIR/jdom-1.0.jar" "es.altia.regexlan.externo" "jdom" "1.0"
install_jar "$LIB_DIR/LibreriaTercerosEgim-1.0.jar" "es.altia.regexlan.externo" "LibreriaTercerosEgim" "1.0"
install_jar "$LIB_DIR/resolver-1.0.jar" "es.altia.regexlan.externo" "resolver" "1.0"
install_jar "$LIB_DIR/saaj-1.0.jar" "es.altia.regexlan.externo" "saaj" "1.0"
install_jar "$LIB_DIR/sax-1.0.jar" "es.altia.regexlan.externo" "sax" "1.0"
install_jar "$LIB_DIR/saxpath-1.0.jar" "es.altia.regexlan.externo" "saxpath" "1.0"
install_jar "$LIB_DIR/unittest-1.0.jar" "es.altia.regexlan.externo" "unittest" "1.0"
install_jar "$LIB_DIR/verifcert-1.0.jar" "es.altia.regexlan.externo" "verifcert" "1.0"
install_jar "$LIB_DIR/webservices-api-1.0.jar" "es.altia.regexlan.externo" "webservices-api" "1.0"
install_jar "$LIB_DIR/webservices-extra-1.0.jar" "es.altia.regexlan.externo" "webservices-extra" "1.0"
install_jar "$LIB_DIR/webservices-extra-api-1.0.jar" "es.altia.regexlan.externo" "webservices-extra-api" "1.0"
install_jar "$LIB_DIR/webservices-tools-1.0.jar" "es.altia.regexlan.externo" "webservices-tools" "1.0"
install_jar "$LIB_DIR/bcpkix-jdk15on-1.0.jar" "es.altia.regexlan.externo" "bcpkix-jdk15on" "1.0"
install_jar "$LIB_DIR/FirmaRedClienteSW-1.0.jar" "es.altia.regexlan.externo" "FirmaRedClienteSW" "1.0"
install_jar "$LIB_DIR/mail-1.4.jar" "es.altia.regexlan.externo" "mail" "1.4"

# Install dependencies from es.altia.regexlan.utilidades group
echo ""
echo "Installing es.altia.regexlan.utilidades dependencies..."
install_jar "$LIB_DIR/formsToSGE-2.16.jar" "es.altia.regexlan.utilidades" "formsToSGE" "2.16"
install_jar "$LIB_DIR/interfazXML-1.0.jar" "es.altia.regexlan.utilidades" "interfazXML" "1.0"
install_jar "$LIB_DIR/swtramite-1.0.jar" "es.altia.regexlan.utilidades" "swtramite" "1.0"
install_jar "$LIB_DIR/documentosTramitacionAlfresco-1.1.jar" "es.altia.regexlan.utilidades" "documentosTramitacionAlfresco" "1.1"
install_jar "$LIB_DIR/afirma-serialization-1.0.jar" "es.altia.regexlan.utilidades" "afirma-serialization" "1.0"
install_jar "$LIB_DIR/AltiaX509-1.0.jar" "es.altia.regexlan.utilidades" "AltiaX509" "1.0"
install_jar "$LIB_DIR/altia_auditoria-1.0.jar" "es.altia.regexlan.utilidades" "altia_auditoria" "1.0"
install_jar "$LIB_DIR/altia-1.0.jar" "es.altia.regexlan.utilidades" "altia" "1.0"
install_jar "$LIB_DIR/ClienteWSAltaPersonaFisica-1.0.jar" "es.altia.regexlan.utilidades" "ClienteWSAltaPersonaFisica" "1.0"
install_jar "$LIB_DIR/ClienteWSBusquedaPersonaFisica-1.0.jar" "es.altia.regexlan.utilidades" "ClienteWSBusquedaPersonaFisica" "1.0"
install_jar "$LIB_DIR/ClienteWSNotificaciones-1.0.jar" "es.altia.regexlan.utilidades" "ClienteWSNotificaciones" "1.0"
install_jar "$LIB_DIR/ClienteWSSharePointNextRet-1.0.jar" "es.altia.regexlan.utilidades" "ClienteWSSharePointNextRet" "1.0"
install_jar "$LIB_DIR/lib_serialization_telematic_head-1.0.jar" "es.altia.regexlan.utilidades" "lib_serialization_telematic_head" "1.0"
install_jar "$LIB_DIR/lib_ws_cliente_telematic-1.0.jar" "es.altia.regexlan.utilidades" "lib_ws_cliente_telematic" "1.0"
install_jar "$LIB_DIR/lib_ws_cliente_telematic_admin-1.0.jar" "es.altia.regexlan.utilidades" "lib_ws_cliente_telematic_admin" "1.0"
install_jar "$LIB_DIR/lib_ws_cliente_telematic_Head-1.0.jar" "es.altia.regexlan.utilidades" "lib_ws_cliente_telematic_Head" "1.0"
install_jar "$LIB_DIR/license-1.0.jar" "es.altia.regexlan.utilidades" "license" "1.0"
install_jar "$LIB_DIR/pki_viaFirma-1.0.jar" "es.altia.regexlan.utilidades" "pki_viaFirma" "1.0"
install_jar "$LIB_DIR/RE_Interfaces-1.0.jar" "es.altia.regexlan.utilidades" "RE_Interfaces" "1.0"
install_jar "$LIB_DIR/SLE_Comun-1.0.jar" "es.altia.regexlan.utilidades" "SLE_Comun" "1.0"
install_jar "$LIB_DIR/SLE_Comun_Notificacion-1.0.jar" "es.altia.regexlan.utilidades" "SLE_Comun_Notificacion" "1.0"
install_jar "$LIB_DIR/SLE_j6_afirma5_core-3.0.jar" "es.altia.regexlan.utilidades" "SLE_j6_afirma5_core" "3.0"
install_jar "$LIB_DIR/SLE_PlataformaPKI_Altia-1.1.jar" "es.altia.regexlan.utilidades" "SLE_PlataformaPKI_Altia" "1.1"
install_jar "$LIB_DIR/SLE_Plugin_PlataformaPKI-1.0.jar" "es.altia.regexlan.utilidades" "SLE_Plugin_PlataformaPKI" "1.0"
install_jar "$LIB_DIR/xbeanBeaXml-1.0.jar" "es.altia.regexlan.utilidades" "xbeanBeaXml" "1.0"
install_jar "$LIB_DIR/Altia-Jaas-1.0-LANBIDE.jar" "es.altia.regexlan.utilidades" "Altia-Jaas" "1.0"
install_jar "$LIB_DIR/aspectjrt-1.0.jar" "es.altia.regexlan.utilidades" "aspectjrt" "1.0"
install_jar "$LIB_DIR/aspectjweaver-1.0.jar" "es.altia.regexlan.utilidades" "aspectjweaver" "1.0"
install_jar "$LIB_DIR/WSRegistroESClient-19.00.00.jar" "es.altia.regexlan.utilidades" "WSRegistroESClient" "19.00.00"
install_jar "$LIB_DIR/commons-logging-old-1.0.4.jar" "es.altia.regexlan.utilidades" "commons-logging-old" "1.0.4"
install_jar "$LIB_DIR/conversorEni-1.0.0.jar" "es.altia.regexlan.utilidades" "conversorEni" "1.0.0"
install_jar "$LIB_DIR/ehcache-core-2.5.2.jar" "es.altia.regexlan.utilidades" "ehcache-core" "2.5.2"
install_jar "$LIB_DIR/gestion-numeracion-anotacion-1.0.jar" "es.altia.regexlan.utilidades" "gestion-numeracion-anotacion" "1.0"
install_jar "$LIB_DIR/jaxb-impl-2.2.4.jar" "es.altia.regexlan.utilidades" "jaxb-impl" "2.2.4"
install_jar "$LIB_DIR/jstl-1.0-LANBIDE.jar" "es.altia.regexlan.utilidades" "jstl" "1.0"
install_jar "$LIB_DIR/jta-1.0-LANBIDE.jar" "es.altia.regexlan.utilidades" "jta" "1.0"
install_jar "$LIB_DIR/libloader-0.2.2.jar" "es.altia.regexlan.utilidades" "libloader" "0.2.2"
install_jar "$LIB_DIR/libpixie-1.2.2.jar" "es.altia.regexlan.utilidades" "libpixie" "1.2.2"
install_jar "$LIB_DIR/MELANBIDE_DOKUSI_1.5.3.jar" "es.altia.regexlan.utilidades" "MELANBIDE_DOKUSI" "1.6.1"
install_jar "$LIB_DIR/org.springframework.context-1.0-LANBIDE.jar" "es.altia.regexlan.utilidades" "org-springframework-context" "1.0"
install_jar "$LIB_DIR/pixie-0.8.6.jar" "es.altia.regexlan.utilidades" "pixie" "0.8.6"
install_jar "$LIB_DIR/servlet-api-1.0-LANBIDE.jar" "es.altia.regexlan.utilidades" "servlet-api" "1.0"
install_jar "$LIB_DIR/SLE-PlataformaPKI-afirmaIntegra.jar" "es.altia.regexlan.utilidades" "SLE-PlataformaPKI-afirmaIntegra" "1.0"
install_jar "$LIB_DIR/SLE-PlataformaPKI-asf.jar" "es.altia.regexlan.utilidades" "SLE-PlataformaPKI-asf" "1.0"
install_jar "$LIB_DIR/spring-core-2.5.6.jar" "es.altia.regexlan.utilidades" "spring-core" "2.5.6"
install_jar "$LIB_DIR/spring-test-1.0-LANBIDE.jar" "es.altia.regexlan.utilidades" "spring-test" "1.0"
install_jar "$LIB_DIR/spring-web-2.0.5.jar" "es.altia.regexlan.utilidades" "spring-web" "2.0.5"
install_jar "$LIB_DIR/spring-1.0-LANBIDE.jar" "es.altia.regexlan.utilidades" "spring" "1.0"
install_jar "$LIB_DIR/sqljdbc-1.0-LANBIDE.jar" "es.altia.regexlan.utilidades" "sqljdbc" "1.0"
install_jar "$LIB_DIR/standard-1.0-LANBIDE.jar" "es.altia.regexlan.utilidades" "standard" "1.0"
install_jar "$LIB_DIR/taglibs-log-1.0-LANBIDE.jar" "es.altia.regexlan.utilidades" "taglibs-log" "1.0"
install_jar "$LIB_DIR/WSTerceroClient.jar" "es.altia.regexlan.utilidades" "WSTerceroClient" "19.00.00"
install_jar "$LIB_DIR/xmlparserv2-1.0-LANBIDE.jar" "es.altia.regexlan.utilidades" "xmlparserv2" "1.0"
install_jar "$LIB_DIR/WSTramitacion_PlugxProc-1.0.jar" "es.altia.regexlan.utilidades" "WSTramitacion_PlugxProc" "1.0"
install_jar "$LIB_DIR/valnif-1.0.jar" "es.altia.regexlan.utilidades" "valnif" "1.0"
install_jar "$LIB_DIR/ClienteWSFicheroAltaEspecialidadesFormacion-1.0.jar" "es.altia.regexlan.utilidades" "ClienteWSFicheroAltaEspecialidadesFormacion" "1.0"
install_jar "$LIB_DIR/ClienteWSRegistroCentrosFormacion-1.0.jar" "es.altia.regexlan.utilidades" "ClienteWSRegistroCentrosFormacion" "1.0"
install_jar "$LIB_DIR/ClienteWSExpedientesFormacion-1.0.jar" "es.altia.regexlan.utilidades" "ClienteWSExpedientesFormacion" "1.0"
install_jar "$LIB_DIR/INTEROP_EJIE_SERVICE-1.0.jar" "es.altia.regexlan.utilidades" "INTEROP_EJIE_SERVICE" "1.0"

# Install dependencies from es.lanbide group
echo ""
echo "Installing es.lanbide dependencies..."
install_jar "$LIB_DIR/lan6gestionerrores.jar" "es.lanbide.gestionErrores" "lan6gestionerrores" "1.8.5"
install_jar "$LIB_DIR/LAN_WSLan6ConfigManager_client.jar" "es.lanbide.lan6.config" "LAN_WSLan6ConfigManager_client" "1.0.4"
install_jar "$LIB_DIR/LAN_X43RegistroRepresentantesWSSUser_client.jar" "es.lanbide.adaptadores" "LAN_X43RegistroRepresentantesWSSUser_client" "1.0"
install_jar "$LIB_DIR/LAN_X43FirmaWSSUser_client.jar" "es.lanbide.adaptadores" "LAN_X43FirmaWSSUser_client" "1.0.1"
install_jar "$LIB_DIR/LAN_X43ToolkitWSSUser_client.jar" "es.lanbide.adaptadores" "LAN_X43ToolkitWSSUser_client" "1.0.0"
install_jar "$LIB_DIR/AdaptadoresPlateaLan6-2.2.2.jar" "es.lanbide.lan6" "AdaptadoresPlateaLan6" "2.2.3"
install_jar "$LIB_DIR/EikaConsultaTerceros-1.0.2.jar" "es.lanbide.lan6" "EikaConsultaTerceros" "1.0.2"
install_jar "$LIB_DIR/LanOTDDFFNisae-1.0.1.jar" "net.lanbide.interoperability.librerias" "LanOTDDFFNisae" "1.0.1"
install_jar "$LIB_DIR/RdR_Esquemas-1.2.jar" "es.lanbide.adaptadores" "RdR_Esquemas" "1.2"
install_jar "$LIB_DIR/Rri_Esquemas-1.0.jar" "es.lanbide.adaptadores" "Rri_Esquemas" "1.0"
install_jar "$LIB_DIR/LanTGSSNisae-1.0.0.jar" "net.lanbide.interoperability.librerias" "LanTGSSNisae" "1.0.0"
install_jar "$LIB_DIR/X43ExpElecEsquemas-1.0.jar" "es.lanbide.adaptadores" "X43ExpElecEsquemas" "1.0"

echo ""
echo "=========================================="
echo "Installation complete!"
echo "=========================================="
echo ""
echo "All local dependencies have been installed to the local Maven repository."
echo "You can now run: mvn compile"
