-- =====================================================
-- Script de datos iniciales para MELANBIDE11_SUBVENCION_REF
-- Año 2025 - Cuantías de subvención DEM50
-- =====================================================

-- Limpiar datos anteriores del año 2025 si existen
DELETE FROM MELANBIDE11_SUBVENCION_REF WHERE ANIO = 2025;

-- =====================================================
-- PERFILES CON TITULACIÓN FP2 (Formación Profesional 2º Grado)
-- =====================================================

-- Hombre, menor de 55, sin discapacidad
INSERT INTO MELANBIDE11_SUBVENCION_REF (ANIO, TITULACION, MUJER, MAYOR_55, DISCAPACIDAD, TIPO_CONTRATO, IMPORTE, BASE_12_MESES, USUARIO_CREACION)
VALUES (2025, 'FP2', 'N', 'N', 'N', '', 3000.00, 'S', 'SYSTEM');

-- Mujer, menor de 55, sin discapacidad
INSERT INTO MELANBIDE11_SUBVENCION_REF (ANIO, TITULACION, MUJER, MAYOR_55, DISCAPACIDAD, TIPO_CONTRATO, IMPORTE, BASE_12_MESES, USUARIO_CREACION)
VALUES (2025, 'FP2', 'S', 'N', 'N', '', 3500.00, 'S', 'SYSTEM');

-- Hombre, mayor de 55, sin discapacidad
INSERT INTO MELANBIDE11_SUBVENCION_REF (ANIO, TITULACION, MUJER, MAYOR_55, DISCAPACIDAD, TIPO_CONTRATO, IMPORTE, BASE_12_MESES, USUARIO_CREACION)
VALUES (2025, 'FP2', 'N', 'S', 'N', '', 3800.00, 'S', 'SYSTEM');

-- Mujer, mayor de 55, sin discapacidad
INSERT INTO MELANBIDE11_SUBVENCION_REF (ANIO, TITULACION, MUJER, MAYOR_55, DISCAPACIDAD, TIPO_CONTRATO, IMPORTE, BASE_12_MESES, USUARIO_CREACION)
VALUES (2025, 'FP2', 'S', 'S', 'N', '', 4200.00, 'S', 'SYSTEM');

-- Hombre, menor de 55, con discapacidad
INSERT INTO MELANBIDE11_SUBVENCION_REF (ANIO, TITULACION, MUJER, MAYOR_55, DISCAPACIDAD, TIPO_CONTRATO, IMPORTE, BASE_12_MESES, USUARIO_CREACION)
VALUES (2025, 'FP2', 'N', 'N', 'S', '', 4000.00, 'S', 'SYSTEM');

-- Mujer, menor de 55, con discapacidad
INSERT INTO MELANBIDE11_SUBVENCION_REF (ANIO, TITULACION, MUJER, MAYOR_55, DISCAPACIDAD, TIPO_CONTRATO, IMPORTE, BASE_12_MESES, USUARIO_CREACION)
VALUES (2025, 'FP2', 'S', 'N', 'S', '', 4500.00, 'S', 'SYSTEM');

-- =====================================================
-- PERFILES CON TITULACIÓN UNIVERSIDAD
-- =====================================================

-- Hombre, menor de 55, sin discapacidad
INSERT INTO MELANBIDE11_SUBVENCION_REF (ANIO, TITULACION, MUJER, MAYOR_55, DISCAPACIDAD, TIPO_CONTRATO, IMPORTE, BASE_12_MESES, USUARIO_CREACION)
VALUES (2025, 'UNIVERSIDAD', 'N', 'N', 'N', '', 4500.00, 'S', 'SYSTEM');

-- Mujer, menor de 55, sin discapacidad
INSERT INTO MELANBIDE11_SUBVENCION_REF (ANIO, TITULACION, MUJER, MAYOR_55, DISCAPACIDAD, TIPO_CONTRATO, IMPORTE, BASE_12_MESES, USUARIO_CREACION)
VALUES (2025, 'UNIVERSIDAD', 'S', 'N', 'N', '', 5000.00, 'S', 'SYSTEM');

-- Hombre, mayor de 55, sin discapacidad
INSERT INTO MELANBIDE11_SUBVENCION_REF (ANIO, TITULACION, MUJER, MAYOR_55, DISCAPACIDAD, TIPO_CONTRATO, IMPORTE, BASE_12_MESES, USUARIO_CREACION)
VALUES (2025, 'UNIVERSIDAD', 'N', 'S', 'N', '', 5200.00, 'S', 'SYSTEM');

-- Mujer, mayor de 55, sin discapacidad
INSERT INTO MELANBIDE11_SUBVENCION_REF (ANIO, TITULACION, MUJER, MAYOR_55, DISCAPACIDAD, TIPO_CONTRATO, IMPORTE, BASE_12_MESES, USUARIO_CREACION)
VALUES (2025, 'UNIVERSIDAD', 'S', 'S', 'N', '', 5700.00, 'S', 'SYSTEM');

-- =====================================================
-- PERFILES SIN TITULACIÓN ESPECÍFICA (BASE)
-- =====================================================

-- Hombre, menor de 55, sin discapacidad
INSERT INTO MELANBIDE11_SUBVENCION_REF (ANIO, TITULACION, MUJER, MAYOR_55, DISCAPACIDAD, TIPO_CONTRATO, IMPORTE, BASE_12_MESES, USUARIO_CREACION)
VALUES (2025, '', 'N', 'N', 'N', '', 2500.00, 'S', 'SYSTEM');

-- Mujer, menor de 55, sin discapacidad
INSERT INTO MELANBIDE11_SUBVENCION_REF (ANIO, TITULACION, MUJER, MAYOR_55, DISCAPACIDAD, TIPO_CONTRATO, IMPORTE, BASE_12_MESES, USUARIO_CREACION)
VALUES (2025, '', 'S', 'N', 'N', '', 3000.00, 'S', 'SYSTEM');

-- Hombre, mayor de 55, sin discapacidad
INSERT INTO MELANBIDE11_SUBVENCION_REF (ANIO, TITULACION, MUJER, MAYOR_55, DISCAPACIDAD, TIPO_CONTRATO, IMPORTE, BASE_12_MESES, USUARIO_CREACION)
VALUES (2025, '', 'N', 'S', 'N', '', 3200.00, 'S', 'SYSTEM');

-- =====================================================
-- AÑO ANTERIOR (2024) - Datos de ejemplo para referencia
-- =====================================================

-- FP2 - Hombre, menor de 55
INSERT INTO MELANBIDE11_SUBVENCION_REF (ANIO, TITULACION, MUJER, MAYOR_55, DISCAPACIDAD, TIPO_CONTRATO, IMPORTE, BASE_12_MESES, USUARIO_CREACION)
VALUES (2024, 'FP2', 'N', 'N', 'N', '', 2800.00, 'S', 'SYSTEM');

-- FP2 - Mujer, menor de 55
INSERT INTO MELANBIDE11_SUBVENCION_REF (ANIO, TITULACION, MUJER, MAYOR_55, DISCAPACIDAD, TIPO_CONTRATO, IMPORTE, BASE_12_MESES, USUARIO_CREACION)
VALUES (2024, 'FP2', 'S', 'N', 'N', '', 3300.00, 'S', 'SYSTEM');

-- Confirmar cambios
COMMIT;

-- Mostrar resumen de datos insertados
SELECT ANIO, COUNT(*) AS NUM_REGLAS
FROM MELANBIDE11_SUBVENCION_REF
GROUP BY ANIO
ORDER BY ANIO DESC;

-- Verificar algunas reglas
SELECT ANIO, TITULACION, 
       CASE MUJER WHEN 'S' THEN 'Mujer' ELSE 'Hombre' END AS SEXO,
       CASE MAYOR_55 WHEN 'S' THEN 'Sí' ELSE 'No' END AS MAYOR_55,
       CASE DISCAPACIDAD WHEN 'S' THEN 'Sí' ELSE 'No' END AS DISCAPACIDAD,
       IMPORTE
FROM MELANBIDE11_SUBVENCION_REF
WHERE ANIO = 2025
ORDER BY TITULACION, MUJER DESC, MAYOR_55 DESC, DISCAPACIDAD DESC;
